"""Initial remote schema
Revision ID: 627df471e18e
Revises: 
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
import sqlmodel

revision: str = '627df471e18e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_banned', sa.Boolean(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('collection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=False),
    sa.Column('cover', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('collection', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_collection_owner_id'), ['owner_id'], unique=False)

    op.create_table('game',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=False),
    sa.Column('steam_appid', sa.Integer(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('cover', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('background', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('extra_images', sa.JSON(), nullable=False),
    sa.Column('play_time', sa.Integer(), nullable=False),
    sa.Column('favorite', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'steam_appid')
    )
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_game_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_game_title'), ['title'], unique=False)

    op.create_table('tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'name')
    )
    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tag_owner_id'), ['owner_id'], unique=False)

    op.create_table('collection_game_link',
    sa.Column('collection_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['collection.id'], ),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.PrimaryKeyConstraint('collection_id', 'game_id')
    )
    op.create_table('game_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('client_session_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('iniciada_em', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.Column('encerrada_em', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.Column('duracao_segundos', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'client_session_id')
    )
    with op.batch_alter_table('game_session', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_game_session_game_id'), ['game_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_game_session_owner_id'), ['owner_id'], unique=False)

    op.create_table('game_tag_link',
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.PrimaryKeyConstraint('game_id', 'tag_id')
    )
    op.create_table('user_rating',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('stars', sa.Float(), nullable=False),
    sa.Column('gameplay', sa.Integer(), nullable=True),
    sa.Column('graphics', sa.Integer(), nullable=True),
    sa.Column('story', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'game_id')
    )
    with op.batch_alter_table('user_rating', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_rating_game_id'), ['game_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_rating_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_rating', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_rating_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_rating_game_id'))

    op.drop_table('user_rating')
    op.drop_table('game_tag_link')
    with op.batch_alter_table('game_session', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_game_session_owner_id'))
        batch_op.drop_index(batch_op.f('ix_game_session_game_id'))

    op.drop_table('game_session')
    op.drop_table('collection_game_link')
    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tag_owner_id'))

    op.drop_table('tag')
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_game_title'))
        batch_op.drop_index(batch_op.f('ix_game_owner_id'))

    op.drop_table('game')
    with op.batch_alter_table('collection', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_collection_owner_id'))

    op.drop_table('collection')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
